"""empty message

Revision ID: 0ea877cfa3d9
Revises: 7669bd5bf3b4
Create Date: 2026-02-25 14:29:47.800761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea877cfa3d9'
down_revision: Union[str, Sequence[str], None] = '7669bd5bf3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repetitions', sa.Column('iteration', sa.Integer(), nullable=True))
    op.add_column('repetitions', sa.Column('next_review_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repetitions', 'next_review_at')
    op.drop_column('repetitions', 'iteration')
    # ### end Alembic commands ###
