"""empty message

Revision ID: 7669bd5bf3b4
Revises: 202ecc732a97
Create Date: 2026-02-24 15:05:58.744798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7669bd5bf3b4'
down_revision: Union[str, Sequence[str], None] = '202ecc732a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('repetitions_user_id_fkey'), 'repetitions', type_='foreignkey')
    op.drop_column('repetitions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repetitions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('repetitions_user_id_fkey'), 'repetitions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'user_id')
    # ### end Alembic commands ###
